param(
    [string]$OutputPath = ".env.generated",
    [string]$AdminLogin = "admin",
    [int]$Iterations = 600000
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function New-UrlSafeBase64([int]$ByteCount) {
    $bytes = [byte[]]::new($ByteCount)
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    return [Convert]::ToBase64String($bytes).Replace('+', '-').Replace('/', '_')
}

$apiKey = New-UrlSafeBase64 32
$accountsEncryptKey = New-UrlSafeBase64 32
$adminPassword = New-UrlSafeBase64 18
$salt = New-UrlSafeBase64 12

$derive = [System.Security.Cryptography.Rfc2898DeriveBytes]::new(
    $adminPassword,
    [System.Text.Encoding]::UTF8.GetBytes($salt),
    $Iterations,
    [System.Security.Cryptography.HashAlgorithmName]::SHA256
)
$hashHex = [BitConverter]::ToString($derive.GetBytes(32)).Replace('-', '').ToLowerInvariant()
$adminPasswordHash = "pbkdf2_sha256`$${Iterations}`$${salt}`$${hashHex}"

$lines = @(
    "# Generated by scripts/bootstrap-shared-env.ps1",
    "API_KEY=$apiKey",
    "ADMIN_LOGIN=$AdminLogin",
    "ADMIN_PASSWORD_HASH=$adminPasswordHash",
    "ACCOUNTS_ENCRYPT_KEY=$accountsEncryptKey",
    "HF_TOKEN=REPLACE_WITH_HF_TOKEN"
)

Set-Content -Path $OutputPath -Value $lines -Encoding UTF8
Write-Host "Generated shared env file: $OutputPath"
Write-Host "Admin login: $AdminLogin"
Write-Host "Admin password (save it now): $adminPassword"
Write-Host "Next: set HF_TOKEN and copy vars to VM env (/opt/gooni/admin.env)."
