#!/usr/bin/env bash
set -euo pipefail

OUT_PATH="${1:-.env.generated}"
ADMIN_LOGIN="${ADMIN_LOGIN:-admin}"
ITERATIONS="${ITERATIONS:-600000}"

python - "$OUT_PATH" "$ADMIN_LOGIN" "$ITERATIONS" <<'PY'
import base64
import hashlib
import os
import secrets
import sys

out_path = sys.argv[1]
admin_login = sys.argv[2]
iterations = int(sys.argv[3])

def b64url(n: int) -> str:
    return base64.urlsafe_b64encode(os.urandom(n)).decode("ascii")

api_key = secrets.token_urlsafe(32)
accounts_encrypt_key = b64url(32)
admin_password = secrets.token_urlsafe(18)
salt = secrets.token_urlsafe(12)
digest = hashlib.pbkdf2_hmac("sha256", admin_password.encode("utf-8"), salt.encode("utf-8"), iterations).hex()
admin_password_hash = f"pbkdf2_sha256${iterations}${salt}${digest}"

lines = [
    "# Generated by scripts/bootstrap-shared-env.sh",
    f"API_KEY={api_key}",
    f"ADMIN_LOGIN={admin_login}",
    f"ADMIN_PASSWORD_HASH={admin_password_hash}",
    f"ACCOUNTS_ENCRYPT_KEY={accounts_encrypt_key}",
    "HF_TOKEN=REPLACE_WITH_HF_TOKEN",
]
with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Generated shared env file: {out_path}")
print(f"Admin login: {admin_login}")
print(f"Admin password (save it now): {admin_password}")
print("Next: set HF_TOKEN and copy vars to VM env (/opt/gooni/admin.env).")
PY
